// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmsGatewayClient is the client API for SmsGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsGatewayClient interface {
	// Sends a greeting
	CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error)
	CreateSmsTemplate(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*TemplateReply, error)
	QuerySmsTemplate(ctx context.Context, in *QuerySmsTemplateRequest, opts ...grpc.CallOption) (*CommonReply, error)
}

type smsGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsGatewayClient(cc grpc.ClientConnInterface) SmsGatewayClient {
	return &smsGatewayClient{cc}
}

func (c *smsGatewayClient) CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/SmsBase.SmsGateway/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsGatewayClient) CreateSmsTemplate(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*TemplateReply, error) {
	out := new(TemplateReply)
	err := c.cc.Invoke(ctx, "/SmsBase.SmsGateway/CreateSmsTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsGatewayClient) QuerySmsTemplate(ctx context.Context, in *QuerySmsTemplateRequest, opts ...grpc.CallOption) (*CommonReply, error) {
	out := new(CommonReply)
	err := c.cc.Invoke(ctx, "/SmsBase.SmsGateway/QuerySmsTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsGatewayServer is the server API for SmsGateway service.
// All implementations must embed UnimplementedSmsGatewayServer
// for forward compatibility
type SmsGatewayServer interface {
	// Sends a greeting
	CreateMessage(context.Context, *MessageRequest) (*MessageReply, error)
	CreateSmsTemplate(context.Context, *TemplateRequest) (*TemplateReply, error)
	QuerySmsTemplate(context.Context, *QuerySmsTemplateRequest) (*CommonReply, error)
	mustEmbedUnimplementedSmsGatewayServer()
}

// UnimplementedSmsGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedSmsGatewayServer struct {
}

func (UnimplementedSmsGatewayServer) CreateMessage(context.Context, *MessageRequest) (*MessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedSmsGatewayServer) CreateSmsTemplate(context.Context, *TemplateRequest) (*TemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSmsTemplate not implemented")
}
func (UnimplementedSmsGatewayServer) QuerySmsTemplate(context.Context, *QuerySmsTemplateRequest) (*CommonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySmsTemplate not implemented")
}
func (UnimplementedSmsGatewayServer) mustEmbedUnimplementedSmsGatewayServer() {}

// UnsafeSmsGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsGatewayServer will
// result in compilation errors.
type UnsafeSmsGatewayServer interface {
	mustEmbedUnimplementedSmsGatewayServer()
}

func RegisterSmsGatewayServer(s grpc.ServiceRegistrar, srv SmsGatewayServer) {
	s.RegisterService(&SmsGateway_ServiceDesc, srv)
}

func _SmsGateway_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsGatewayServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmsBase.SmsGateway/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsGatewayServer).CreateMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsGateway_CreateSmsTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsGatewayServer).CreateSmsTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmsBase.SmsGateway/CreateSmsTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsGatewayServer).CreateSmsTemplate(ctx, req.(*TemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsGateway_QuerySmsTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySmsTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsGatewayServer).QuerySmsTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmsBase.SmsGateway/QuerySmsTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsGatewayServer).QuerySmsTemplate(ctx, req.(*QuerySmsTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmsGateway_ServiceDesc is the grpc.ServiceDesc for SmsGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmsGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SmsBase.SmsGateway",
	HandlerType: (*SmsGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _SmsGateway_CreateMessage_Handler,
		},
		{
			MethodName: "CreateSmsTemplate",
			Handler:    _SmsGateway_CreateSmsTemplate_Handler,
		},
		{
			MethodName: "QuerySmsTemplate",
			Handler:    _SmsGateway_QuerySmsTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grpc.proto",
}
